import React from 'react';
import Link from 'next/link';
import Footer from '../components/Footer';

export default function ImageCredits() {
  return (
    <main className="bg-white text-gray-800 font-sans min-h-screen">
      <div className="h-1.5 bg-gradient-to-r from-blue-600 via-white to-red-500"></div>
      <section className="max-w-4xl mx-auto px-4 py-12">
        <h1 className="text-3xl md:text-4xl font-bold text-blue-900 mb-4">Image Credits</h1>
        <p className="text-gray-700 mb-8 leading-relaxed text-base md:text-lg">
          The location photographs on our service-area pages are used under Creative Commons licenses. We are grateful to the photographers who made them available. Each image is credited below with its author, license, and source.
        </p>
        <ul className="list-none pl-0">
            <li className="mb-3 text-gray-700 leading-relaxed"><strong className="text-blue-900">Splendora, TX:</strong> &quot;Splendora Welcome Sign&quot; by Stedil, licensed under CC BY-SA 4.0, via Wikimedia Commons. <a href="https://commons.wikimedia.org/wiki/File:Splendora_Welcome_Sign.jpg" target="_blank" rel="nofollow noopener noreferrer" className="text-blue-600 hover:underline">View source</a>. Image resized and cropped for display.</li>
            <li className="mb-3 text-gray-700 leading-relaxed"><strong className="text-blue-900">Conroe, TX:</strong> Downtown Conroe, Texas by Renelibrary, via Wikimedia Commons, licensed under CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/) <a href="https://commons.wikimedia.org/wiki/File:Downtown_Conroe_1_Wiki.jpg" target="_blank" rel="nofollow noopener noreferrer" className="text-blue-600 hover:underline">View source</a>. Image resized and cropped for display.</li>
            <li className="mb-3 text-gray-700 leading-relaxed"><strong className="text-blue-900">The Woodlands, TX:</strong> &quot;Woodlands Waterway&quot; by Photolitherland (via Wikimedia Commons), licensed under CC BY-SA 3.0. <a href="https://commons.wikimedia.org/wiki/File:Woodlands_Waterway.jpg" target="_blank" rel="nofollow noopener noreferrer" className="text-blue-600 hover:underline">View source</a>. Image resized and cropped for display.</li>
            <li className="mb-3 text-gray-700 leading-relaxed"><strong className="text-blue-900">Spring, TX:</strong> Old Town Spring, Texas by Renelibrary, licensed under CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/), via Wikimedia Commons. <a href="https://commons.wikimedia.org/wiki/File:Old_Town_Spring_Wiki_1.jpg" target="_blank" rel="nofollow noopener noreferrer" className="text-blue-600 hover:underline">View source</a>. Image resized and cropped for display.</li>
            <li className="mb-3 text-gray-700 leading-relaxed"><strong className="text-blue-900">Montgomery, TX:</strong> Montgomery, Texas Historic Business District by Stedil, via Wikimedia Commons, licensed under CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/) <a href="https://commons.wikimedia.org/wiki/File:Montgomery_Business_District.jpg" target="_blank" rel="nofollow noopener noreferrer" className="text-blue-600 hover:underline">View source</a>. Image resized and cropped for display.</li>
            <li className="mb-3 text-gray-700 leading-relaxed"><strong className="text-blue-900">Willis, TX:</strong> Photo: HIM Nguyen, City Hall of Willis, Texas, via Wikimedia Commons, CC BY-SA 3.0 <a href="https://commons.wikimedia.org/wiki/File:City_Hall_of_Willis,_Texas,_South_View.jpg" target="_blank" rel="nofollow noopener noreferrer" className="text-blue-600 hover:underline">View source</a>. Image resized and cropped for display.</li>
            <li className="mb-3 text-gray-700 leading-relaxed"><strong className="text-blue-900">Magnolia, TX:</strong> Photo: Magnolia Historic Depot by Stedil, via Wikimedia Commons, licensed under CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/). <a href="https://commons.wikimedia.org/wiki/File:Magnolia_Historic_Depot.jpg" target="_blank" rel="nofollow noopener noreferrer" className="text-blue-600 hover:underline">View source</a>. Image resized and cropped for display.</li>
            <li className="mb-3 text-gray-700 leading-relaxed"><strong className="text-blue-900">Tomball, TX:</strong> First Baptist Church, Tomball, Texas by Michael Martin (Flickr: pinemikey), licensed under CC BY-SA 2.0. Source: https://commons.wikimedia.org/wiki/File:First_Baptist_Church_Tomball_-_Flickr_-_pinemikey.jpg <a href="https://commons.wikimedia.org/wiki/File:First_Baptist_Church_Tomball_-_Flickr_-_pinemikey.jpg" target="_blank" rel="nofollow noopener noreferrer" className="text-blue-600 hover:underline">View source</a>. Image resized and cropped for display.</li>
            <li className="mb-3 text-gray-700 leading-relaxed"><strong className="text-blue-900">New Caney, TX:</strong> Photo: Montgomery County R.B. Tullis Branch Library, New Caney, Texas by Stedil (Wikimedia Commons), licensed under CC BY-SA 4.0. Source: https://commons.wikimedia.org/wiki/File:New_Caney_Library_and_Commerce.jpg <a href="https://commons.wikimedia.org/wiki/File:New_Caney_Library_and_Commerce.jpg" target="_blank" rel="nofollow noopener noreferrer" className="text-blue-600 hover:underline">View source</a>. Image resized and cropped for display.</li>
            <li className="mb-3 text-gray-700 leading-relaxed"><strong className="text-blue-900">Porter, TX:</strong> Porter Post Office by Stedil, via Wikimedia Commons, licensed under CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0). Source: https://commons.wikimedia.org/wiki/File:Porter_Post_Office.jpg <a href="https://commons.wikimedia.org/wiki/File:Porter_Post_Office.jpg" target="_blank" rel="nofollow noopener noreferrer" className="text-blue-600 hover:underline">View source</a>. Image resized and cropped for display.</li>
            <li className="mb-3 text-gray-700 leading-relaxed"><strong className="text-blue-900">Cut and Shoot, TX:</strong> Cut and Shoot City Hall by DoyleWelborn, licensed under CC BY-SA 3.0 (https://creativecommons.org/licenses/by-sa/3.0/), via Wikimedia Commons. <a href="https://commons.wikimedia.org/wiki/File:Cut_and_Shoot_City_Hall.jpg" target="_blank" rel="nofollow noopener noreferrer" className="text-blue-600 hover:underline">View source</a>. Image resized and cropped for display.</li>
            <li className="mb-3 text-gray-700 leading-relaxed"><strong className="text-blue-900">Shenandoah, TX:</strong> Photo: &quot;City of Shenandoah, Texas sign&quot; by Stedil, via Wikimedia Commons, licensed under CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/). Source: https://commons.wikimedia.org/wiki/File:Shenandoah_sign.jpg <a href="https://commons.wikimedia.org/wiki/File:Shenandoah_sign.jpg" target="_blank" rel="nofollow noopener noreferrer" className="text-blue-600 hover:underline">View source</a>. Image resized and cropped for display.</li>
        </ul>
        <div className="mt-10">
          <Link href="/" className="text-blue-600 hover:underline">Back to Home</Link>
        </div>
      </section>
      <Footer />
    </main>
  );
}
